In [2]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action='ignore', category=np.VisibleDeprecationWarning)

## New material

### Comparison Expressions result in a `bool` - fill in the table

In [ ]:
x = 3 
y = 2

In [ ]:
x == y

In [ ]:
x == y + 1

In [ ]:
x != y

In [ ]:
2 < x < 5

In [ ]:
y >= x - 1

In [ ]:
y > x - 1

#### `=` and `==` are different!!!

In [ ]:
x = y

In [ ]:
x

In [ ]:
y

In [ ]:
x = 3 
y = 2
x == y

### `True` counts as `1`, `False` counts as `0`

In [4]:
z = make_array('Jeremy', 'DeNero', 'Jeremy')
z

array(['Jeremy', 'DeNero', 'Jeremy'],
      dtype='<U6')

In [5]:
z == "Jeremy"

array([ True, False,  True], dtype=bool)

In [ ]:
sum(z == "Jeremy")

In [6]:
z == "Jeremy"

array([ True, False,  True], dtype=bool)

In [ ]:
np.average(z == "Jeremy")

In [8]:
np.average(z == "Jeremy")

0.66666666666666663

In [ ]:
np.arange(3) > 1

In [9]:
make_array(0,1,2) > 1

array([False, False,  True], dtype=bool)

In [11]:
sum(np.arange(3) >= 1)

2

In [ ]:
sum(np.arange(4) <= 1) == 2

In [14]:
sum(make_array(0,1,2,3) <= 1) == 2

True

### Control your computations with an `if` statement

In [16]:
def sign(x):
    """determines the sign (+/-) of a numeric input"""
    if x > 0:
        return 'Positive'
    
    elif x < 0:
        return 'Negative'
    
    elif x == 0:
        return 'Neither positive nor negative'

In [17]:
sign(1)

'Positive'

In [18]:
sign(-1)

'Negative'

In [19]:
sign(0)

'Neither positive nor negative'

In [20]:
sign('-1')

TypeError: '>' not supported between instances of 'str' and 'int'

https://pollev.com/jeremysanchez

#### Discussion Question: 
- What is the sign of the value of the following expression?

```python
sign(sum(np.arange(4) <= 1) * -2)
```

In [24]:
sign(sum(np.arange(4) <= 1) * -2)

'Negative'

### Control your computations with a `for` loop - examples

#### Slide example

In [ ]:
for i in np.arange(5):
    print("I am counting to 100. I am at " + str(i + 1))

In [ ]:
faculty = make_array('Jeremy', 'DeNero', 'Adhikari')

for i in faculty:
    print(i)

#### Looking forward...

**Task**: flip 100 coins

In [25]:
coin_sides = make_array('heads','tails')

In [31]:
for i in np.arange(100):
    side_landed_on = np.random.choice(coin_sides, replace=True)
    print(side_landed_on)

heads
tails
heads
heads
heads
heads
heads
heads
heads
heads
heads
heads
tails
tails
tails
tails
heads
heads
tails
heads
heads
tails
heads
tails
heads
tails
heads
heads
tails
heads
heads
tails
heads
heads
tails
heads
heads
heads
heads
tails
heads
heads
tails
tails
heads
heads
heads
tails
heads
tails
heads
tails
heads
heads
tails
heads
heads
heads
heads
heads
heads
tails
heads
tails
tails
heads
tails
tails
tails
tails
tails
heads
tails
tails
heads
tails
heads
tails
heads
tails
tails
tails
tails
heads
tails
tails
heads
heads
heads
heads
tails
tails
heads
heads
heads
tails
tails
heads
heads
tails


In [34]:
np.append(numbers, 1)

array([ 1.])

AttributeError: 'numpy.ndarray' object has no attribute 'append'